name: Mobile Tests WDIO

on:
  push:
    branches:
      - main
      - testes-com-CI

jobs:
  mobile-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Dar permissão ao WDIO
        run: chmod +x ./node_modules/.bin/wdio

      - name: Rodar testes mobile
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        run: ./node_modules/.bin/wdio run ./wdio.conf.ts